package com.powernode.crm.settings.mapper;

import com.powernode.crm.settings.domain.DicType;

import java.util.List;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Oct 30 09:42:14 CST 2023
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Oct 30 09:42:14 CST 2023
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Oct 30 09:42:14 CST 2023
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Oct 30 09:42:14 CST 2023
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Oct 30 09:42:14 CST 2023
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon Oct 30 09:42:14 CST 2023
     */
    int updateByPrimaryKey(DicType record);

    /**
     * 查询所有字典类型
     * @return
     */
    List<DicType> selectAllDicType();
}
